name: Java CI/CD

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Releases"
        required: false
  push:
    tags:
      - "v*" 

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build with Maven
        run: mvn clean compile assembly:single

      - name: Get version
        id: get_version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec)" >> $GITHUB_ENV

      - name: Get artifact id
        id: get_artifact_id
        run: echo "ARTIFACT_ID=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' exec:exec)" >> $GITHUB_ENV

      - name: Rename artifact
        run: mv ./target/${{ env.ARTIFACT_ID }}.jar ./target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.event.inputs.release_tag || format('v{0}', env.VERSION) }}"
          RELEASE_NAME="Release ${{ env.VERSION }}"
          
          if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi
          
          gh release create "$TAG_NAME" ./target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar \
            --title "$RELEASE_NAME" \
            --notes "Automated release for version ${{ env.VERSION }}" \
            --target ${{ github.ref_name }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bayuairbenders/mcdash:latest
            bayuairbenders/mcdash:${{ env.VERSION }}
