name: Java CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean compile assembly:single

      - name: Get version
        id: get_version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Get artifact id
        id: get_artifact_id
        run: echo "ARTIFACT_ID=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Rename artifact
        run: mv ./target/${{ env.ARTIFACT_ID }}.jar ./target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar
          path: ./target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar
          retention-days: 90
